module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: default
cabal-file: project.cabal
hidden-packages: EitherT
version: 1
extra-packages: ! 'cpphs-1.17.1

  git: git@github.com:mgsloan/haskell-src-exts.git 46-more-parsers

  th-orphans-0.8

  haskell-src-meta-0.6.0.5'
ghc-args: []
excluded-modules: []
